name: C/C++ CI

on:
  push:
    branches: [ master, jbenden-patch-1 ]
    paths-ignore:
      - contrib/**
      - manpages/**
      - patches/**
  pull_request:
    branches: [ master, jbenden-patch-1 ]
    paths-ignore:
      - contrib/**
      - manpages/**
      - patches/**

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v1
        with:
          packages: autoconf automake bison gcc-core gcc-g++ mingw-runtime mingw-binutils mingw-gcc-core mingw-gcc-g++ mingw-pthreads mingw-w32api libtool make python gettext-devel gettext intltool libiconv pkg-config git wget curl libpcre-devel libssl-devel libsqlite3-devel zlib-devel cmocka unzip zip rsync expect libhwloc-devel ccache

      - name: Create home dir
        run: |
          C:\tools\cygwin\bin\bash.exe --login -c 'env'

      - name: Download AirPcap sources
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "curl -RLO https://dl.aircrack-ng.org/AirPcap_Devpack_4_1_1_1838.zip"

      - name: Verify digest of AirPcap sources
        shell: pwsh
        run: |
          $hashFromFile = Get-FileHash -Path "AirPcap_Devpack_4_1_1_1838.zip" -Algorithm SHA256
          if ($hashFromFile.Hash -ne "86dcde46603cd1229245263499ef9cb4e43ee66cd7219605d30095562888da14") {
            Write-Host "AirPcap failed digest check." -ForegroundColor Red
            $hashFromFile | Format-List
            Break
          }

      - name: Decompress AirPcap sources
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "7z -y x AirPcap_Devpack_4_1_1_1838.zip"

      - name: Perform compilation
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "cp -vfp Airpcap_Devpack/bin/x86/airpcap.dll /cygdrive/c/Windows/System32"
          C:\tools\cygwin\bin\bash.exe -e -l -c "dlltool -D Airpcap_Devpack/bin/x86/airpcap.dll -d build/airpcap.dll.def -l Airpcap_Devpack/bin/x86/libairpcap.dll.a"

      - name: Build w/AirPcap
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "./build/cygwin.sh gcc --enable-maintainer-mode --with-experimental --with-airpcap=/cygdrive/c/projects/aircrack-ng"

      - name: Build w/o AirPcap
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "./build/cygwin.sh gcc --enable-maintainer-mode --with-experimental"
