name: Windows CI

on:
  push:
    branches: [ master, jbenden-patch-1 ]
    paths-ignore:
      - contrib/**
      - manpages/**
      - patches/**
  pull_request:
    branches: [ master, jbenden-patch-1 ]
    paths-ignore:
      - contrib/**
      - manpages/**
      - patches/**

jobs:
  cygwin_32bit:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: C:\tools\cygwin
          key: cygwin_32bit
          # key: ${{ runner.os }}-${{ hashFiles('.github/workflows/windows.yml') }}
    
      - name: Set up Cygwin
        if: steps.cache.outputs.cache-hit != 'true'
        uses: egor-tensin/setup-cygwin@v1
        with:
          platform: x86
          install-dir: C:\tools\cygwin
          packages: |
            autoconf automake bison gcc-core gcc-g++ mingw-runtime mingw-binutils mingw-gcc-core
            mingw-gcc-g++ mingw-pthreads mingw-w32api libtool make python gettext-devel gettext
            intltool libiconv pkg-config git wget curl libpcre-devel libssl-devel libsqlite3-devel
            zlib-devel cmocka unzip zip rsync expect libhwloc-devel ccache

      - name: Create home dir
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          C:\tools\cygwin\bin\bash.exe --login -c 'env'

      - name: Find Cygwin path to workspace
        id: cygwin
        run: |
          function Exec-External {
            param(
              [Parameter(Position=0,Mandatory=1)][scriptblock] $command
            )
            & $command 2>&1 | %{ "$_" }
            if ($LASTEXITCODE -ne 0) {
              throw ("Command returned non-zero error-code ${LASTEXITCODE}: $command")
            }
          }
          $unix_path = (Exec-External {& C:\tools\cygwin\bin\bash.exe --login -e -c "cygpath '${env:GITHUB_WORKSPACE}'"})
          Write-Host "::set-output name=unix_path::${unix_path}"

      - name: Download AirPcap sources
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "cd ${{ steps.cygwin.outputs.unix_path }} && curl -RLO https://dl.aircrack-ng.org/AirPcap_Devpack_4_1_1_1838.zip"

      - name: Verify digest of AirPcap sources
        shell: pwsh
        run: |
          $hashFromFile = Get-FileHash -Path "AirPcap_Devpack_4_1_1_1838.zip" -Algorithm SHA256
          if ($hashFromFile.Hash -ne "86dcde46603cd1229245263499ef9cb4e43ee66cd7219605d30095562888da14") {
            Write-Host "AirPcap failed digest check." -ForegroundColor Red
            $hashFromFile | Format-List
            Break
          }

      - name: Decompress AirPcap sources
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "cd ${{ steps.cygwin.outputs.unix_path }} && 7z -y x AirPcap_Devpack_4_1_1_1838.zip"

      - name: Perform compilation
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "cd ${{ steps.cygwin.outputs.unix_path }} && cp -vfp Airpcap_Devpack/bin/x86/airpcap.dll /cygdrive/c/Windows/System32"
          C:\tools\cygwin\bin\bash.exe -e -l -c "cd ${{ steps.cygwin.outputs.unix_path }} && dlltool -D Airpcap_Devpack/bin/x86/airpcap.dll -d build/airpcap.dll.def -l Airpcap_Devpack/bin/x86/libairpcap.dll.a"

      - name: Build w/AirPcap
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "cd ${{ steps.cygwin.outputs.unix_path }} && ./build/cygwin.sh gcc --enable-maintainer-mode --with-experimental --with-airpcap=/cygdrive/d/a/aircrack-ng/aircrack-ng"

      - name: Build w/o AirPcap
        run: |
          C:\tools\cygwin\bin\bash.exe -e -l -c "cd ${{ steps.cygwin.outputs.unix_path }} && ./build/cygwin.sh gcc --enable-maintainer-mode --with-experimental"
